// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  NEXT_CACHE_WORKERS_KV: KVNamespace;
  NEXT_PUBLIC_APP_URL: string;
  NODE_ENV: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  CLOUDFLARE_DATABASE_ID: string;
  CLOUDFLARE_D1_TOKEN: string;
  DISCORD_CLIENT_ID: string;
  DISCORD_CLIENT_SECRET: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  SECRET_HASH: string;
  MOCK_SEND_EMAIL: string;
  SENDGRID_API_KEY: string;
  EMAIL_SENDER: string;
  SMTP_HOST: string;
  SMTP_PORT: string;
  SMTP_USER: string;
  SMTP_PASSWORD: string;
  DB: D1Database;
  ASSETS: Fetcher;
}
