#:schema node_modules/wrangler/config-schema.json
name = "usabilitree"
main = ".worker-next/index.mjs"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat_v2"]
assets = { directory = ".worker-next/assets", binding = "ASSETS" }
# pages_build_output_dir = ".vercel/output/static"

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
# [placement]
# mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "usabilitree"
database_id = "f1bcde26-e7bf-4246-85e1-e6f93d4bec6e"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "f32cd2319c06420ebb6f17ac0d11ef03"
preview_id = "b43e9638bd314f2ea6b9bdd378aad3f9"

# To use different bindings for preview and production environments, follow the examples below.
# When using environment-specific overrides for bindings, ALL bindings must be specified on a per-environment basis.
# Docs: https://developers.cloudflare.com/pages/functions/wrangler-configuration#environment-specific-overrides

######## PREVIEW environment config ########

# [env.preview.vars]
# API_KEY = "xyz789"

# [[env.preview.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PREVIEW_NAMESPACE_ID>"

######## PRODUCTION environment config ########

# [env.production.vars]
# API_KEY = "abc123"

# [[env.production.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PRODUCTION_NAMESPACE_ID>"
